---
# Source: blogchart/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP  # or ClusterIP, depending on your use case
---
# Source: blogchart/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP  # or ClusterIP, depending on your use case
---
# Source: blogchart/templates/backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "docker.io/ym53/blogbackend:0.1.1"  # Replace with your private image
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-registry-secret  # Reference to the secret created earlier
---
# Source: blogchart/templates/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployhment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: "docker.io/ym5533/blogfrontend:0.1.12"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-secret

